"""Compatibility shim for environments where the published pyairports package is broken."""

# outlines only uses index 3 as the IATA code when building its enum.
AIRPORT_LIST = [
    ("Atlanta", "United States",
     "Hartsfield-Jackson Atlanta International Airport", "ATL"),
    ("Beijing", "China", "Beijing Capital International Airport", "PEK"),
    ("Chicago", "United States", "O'Hare International Airport", "ORD"),
    ("Dallas", "United States", "Dallas Fort Worth International Airport", "DFW"),
    ("Denver", "United States", "Denver International Airport", "DEN"),
    ("Dubai", "United Arab Emirates", "Dubai International Airport", "DXB"),
    ("Frankfurt", "Germany", "Frankfurt Airport", "FRA"),
    ("Guangzhou", "China", "Guangzhou Baiyun International Airport", "CAN"),
    ("Hong Kong", "China", "Hong Kong International Airport", "HKG"),
    ("Istanbul", "Turkey", "Istanbul Airport", "IST"),
    ("Jakarta", "Indonesia", "Soekarno-Hatta International Airport", "CGK"),
    ("London", "United Kingdom", "Heathrow Airport", "LHR"),
    ("Los Angeles", "United States", "Los Angeles International Airport", "LAX"),
    ("Madrid", "Spain", "Adolfo Suarez Madrid-Barajas Airport", "MAD"),
    ("Mumbai", "India", "Chhatrapati Shivaji Maharaj International Airport", "BOM"),
    ("Munich", "Germany", "Munich Airport", "MUC"),
    ("New Delhi", "India", "Indira Gandhi International Airport", "DEL"),
    ("New York", "United States", "John F. Kennedy International Airport", "JFK"),
    ("Paris", "France", "Charles de Gaulle Airport", "CDG"),
    ("San Francisco", "United States", "San Francisco International Airport", "SFO"),
    ("Sao Paulo", "Brazil", "Sao Paulo-Guarulhos International Airport", "GRU"),
    ("Seattle", "United States", "Seattle-Tacoma International Airport", "SEA"),
    ("Seoul", "South Korea", "Incheon International Airport", "ICN"),
    ("Shanghai", "China", "Shanghai Pudong International Airport", "PVG"),
    ("Singapore", "Singapore", "Singapore Changi Airport", "SIN"),
    ("Sydney", "Australia", "Sydney Airport", "SYD"),
    ("Tokyo", "Japan", "Haneda Airport", "HND"),
    ("Toronto", "Canada", "Toronto Pearson International Airport", "YYZ"),
    ("Vancouver", "Canada", "Vancouver International Airport", "YVR"),
    ("Zurich", "Switzerland", "Zurich Airport", "ZRH"),
]
